name: ritam_python_CI

on:
  push
 
env:
  DOCKER_USERNAME: ${{vars.DOCKERHUB_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
  DOCKER_IMAGE: ritamhcltech/docker-git-demo
jobs:
  build-using-docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4.2.2
      - name: Docker login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{env.DOCKER_USERNAME}}
          password: ${{env.DOCKER_PASSWORD}}
      - name: Docker Build
        run: |
          docker build -t $DOCKER_IMAGE:${{github.sha}} .
          docker tag $DOCKER_IMAGE:${{github.sha}} $DOCKER_IMAGE:latest
      - name: Push the Docker Image to Hub
        run: |
          docker push $DOCKER_IMAGE:${{ github.sha }}
          docker push $DOCKER_IMAGE:latest
